### ISSUE TITLE
execbeat to run multiple commands

### ISSUE THREAD

**Issue by wongster80** [christiangalsterer/execbeat#18]
Hi,

I'm unable to run multiple commands with the following execbeat.yml, as this returns only the last command.

 ```
 commands:
    # Each - Commands to execute.
    -
      # Optional cron expression, defines when to execute the command.
      # Default is every 1 minute.
      schedule: "@every 2s"

      # The command to execute by Execbeat
      command: date

      # Optional arguments to be passed to the command to execute
      #args: /proc/vmstat 

      # Type to be published in the 'type' field. For Elasticsearch output,
      # the type defines the document type these entries should be stored
      # in. Default: execbeat
      document_type: execbeat

      schedule: "@every 3s"
      command: uptime
      #args: /home/aw110f/execbeat2.sh
```

output:

{"@timestamp":"2017-04-22T00:06:30.000Z","beat":{"hostname":"vert-dev-node1.ev1.yellowpages.com","name":"vert-dev-node1.ev1.yellowpages.com","version":"3.1.1"},"exec":{"command":"uptime","exitCode":0,"stdout":" 00:06:30 up 134 days,  5:02,  6 users,  load average: 0.48, 0.82, 0.78\n"},"fields":{"env":"DEV"},"tags":["vertica","newt","vmstat"],"type":"execbeat"}
{"@timestamp":"2017-04-22T00:06:33.000Z","beat":{"hostname":"vert-dev-node1.ev1.yellowpages.com","name":"vert-dev-node1.ev1.yellowpages.com","version":"3.1.1"},"exec":{"command":"uptime","exitCode":0,"stdout":" 00:06:33 up 134 days,  5:02,  6 users,  load average: 0.48, 0.82, 0.78\n"},"fields":{"env":"DEV"},"tags":["vertica","newt","vmstat"],"type":"execbeat"}
